#include "HAComponentPropertyConstante.hpp"

namespace HALIB_NAMESPACE
{
    const char PROPERTY_TEMPLATE_STRING[] PROGMEM = "\"%s\":\"%s\"";
    const char PROPERTY_TEMPLATE_OBJECT[] PROGMEM = "\"%s\":%s";

    const char PROP_VALUE_ROOT_TOPIC[] PROGMEM = "~";
    const char PROP_VALUE_ACTION_TOPIC[] PROGMEM = "act_t";
    const char PROP_VALUE_ACTION_TEMPLATE[] PROGMEM = "act_tpl";
    const char PROP_VALUE_AUTOMATION_TYPE[] PROGMEM = "atype";
    const char PROP_VALUE_AUX_COMMAND_TOPIC[] PROGMEM = "aux_cmd_t";
    const char PROP_VALUE_AUX_STATE_TEMPLATE[] PROGMEM = "aux_stat_tpl";
    const char PROP_VALUE_AUX_STATE_TOPIC[] PROGMEM = "aux_stat_t";
    const char PROP_VALUE_AVAILABILITY_TOPIC[] PROGMEM = "avty_t";
    const char PROP_VALUE_AWAY_MODE_COMMAND_TOPIC[] PROGMEM = "away_mode_cmd_t";
    const char PROP_VALUE_AWAY_MODE_STATE_TEMPLATE[] PROGMEM = "away_mode_stat_tpl";
    const char PROP_VALUE_AWAY_MODE_STATE_TOPIC[] PROGMEM = "away_mode_stat_t";
    const char PROP_VALUE_BLUE_TEMPLATE[] PROGMEM = "b_tpl";
    const char PROP_VALUE_BRIGHTNESS_COMMAND_TOPIC[] PROGMEM = "bri_cmd_t";
    const char PROP_VALUE_BRIGHTNESS_SCALE[] PROGMEM = "bri_scl";
    const char PROP_VALUE_BRIGHTNESS_STATE_TOPIC[] PROGMEM = "bri_stat_t";
    const char PROP_VALUE_BRIGHTNESS_TEMPLATE[] PROGMEM = "bri_tpl";
    const char PROP_VALUE_BRIGHTNESS_VALUE_TEMPLATE[] PROGMEM = "bri_val_tpl";
    const char PROP_VALUE_COLOR_TEMP_COMMAND_TEMPLATE[] PROGMEM = "clr_temp_cmd_tpl";
    const char PROP_VALUE_BATTERY_LEVEL_TOPIC[] PROGMEM = "bat_lev_t";
    const char PROP_VALUE_BATTERY_LEVEL_TEMPLATE[] PROGMEM = "bat_lev_tpl";
    const char PROP_VALUE_CHARGING_TOPIC[] PROGMEM = "chrg_t";
    const char PROP_VALUE_CHARGING_TEMPLATE[] PROGMEM = "chrg_tpl";
    const char PROP_VALUE_COLOR_TEMP_COMMAND_TOPIC[] PROGMEM = "clr_temp_cmd_t";
    const char PROP_VALUE_COLOR_TEMP_STATE_TOPIC[] PROGMEM = "clr_temp_stat_t";
    const char PROP_VALUE_COLOR_TEMP_TEMPLATE[] PROGMEM = "clr_temp_tpl";
    const char PROP_VALUE_COLOR_TEMP_VALUE_TEMPLATE[] PROGMEM = "clr_temp_val_tpl";
    const char PROP_VALUE_CLEANING_TOPIC[] PROGMEM = "cln_t";
    const char PROP_VALUE_CLEANING_TEMPLATE[] PROGMEM = "cln_tpl";
    const char PROP_VALUE_COMMAND_OFF_TEMPLATE[] PROGMEM = "cmd_off_tpl";
    const char PROP_VALUE_COMMAND_ON_TEMPLATE[] PROGMEM = "cmd_on_tpl";
    const char PROP_VALUE_COMMAND_TOPIC[] PROGMEM = "cmd_t";
    const char PROP_VALUE_COMMAND_TEMPLATE[] PROGMEM = "cmd_tpl";
    const char PROP_VALUE_CODE_ARM_REQUIRED[] PROGMEM = "cod_arm_req";
    const char PROP_VALUE_CODE_DISARM_REQUIRED[] PROGMEM = "cod_dis_req";
    const char PROP_VALUE_CURRENT_TEMPERATURE_TOPIC[] PROGMEM = "curr_temp_t";
    const char PROP_VALUE_CURRENT_TEMPERATURE_TEMPLATE[] PROGMEM = "curr_temp_tpl";
    const char PROP_VALUE_DEVICE[] PROGMEM = "dev";
    const char PROP_VALUE_DEVICE_CONNECTION[] PROGMEM = "cns";
    const char PROP_VALUE_DEVICE_IDENTIFIER[] PROGMEM = "ids";
    const char PROP_VALUE_DEVICE_MANUFACTURER[] PROGMEM = "mf";
    const char PROP_VALUE_DEVICE_MODEL[] PROGMEM = "mdl";
    const char PROP_VALUE_DEVICE_RELEASE[] PROGMEM = "sw";
    const char PROP_VALUE_DEVICE_CLASS[] PROGMEM = "dev_cla";
    const char PROP_VALUE_DOCKED_TOPIC[] PROGMEM = "dock_t";
    const char PROP_VALUE_DOCKED_TEMPLATE[] PROGMEM = "dock_tpl";
    const char PROP_VALUE_ERROR_TOPIC[] PROGMEM = "err_t";
    const char PROP_VALUE_ERROR_TEMPLATE[] PROGMEM = "err_tpl";
    const char PROP_VALUE_FAN_SPEED_TOPIC[] PROGMEM = "fanspd_t";
    const char PROP_VALUE_FAN_SPEED_TEMPLATE[] PROGMEM = "fanspd_tpl";
    const char PROP_VALUE_FAN_SPEED_LIST[] PROGMEM = "fanspd_lst";
    const char PROP_VALUE_FLASH_TIME_LONG[] PROGMEM = "flsh_tlng";
    const char PROP_VALUE_FLASH_TIME_SHORT[] PROGMEM = "flsh_tsht";
    const char PROP_VALUE_EFFECT_COMMAND_TOPIC[] PROGMEM = "fx_cmd_t";
    const char PROP_VALUE_EFFECT_LIST[] PROGMEM = "fx_list";
    const char PROP_VALUE_EFFECT_STATE_TOPIC[] PROGMEM = "fx_stat_t";
    const char PROP_VALUE_EFFECT_TEMPLATE[] PROGMEM = "fx_tpl";
    const char PROP_VALUE_EFFECT_VALUE_TEMPLATE[] PROGMEM = "fx_val_tpl";
    const char PROP_VALUE_EXPIRE_AFTER[] PROGMEM = "exp_aft";
    const char PROP_VALUE_FAN_MODE_COMMAND_TOPIC[] PROGMEM = "fan_mode_cmd_t";
    const char PROP_VALUE_FAN_MODE_STATE_TEMPLATE[] PROGMEM = "fan_mode_stat_tpl";
    const char PROP_VALUE_FAN_MODE_STATE_TOPIC[] PROGMEM = "fan_mode_stat_t";
    const char PROP_VALUE_FORCE_UPDATE[] PROGMEM = "frc_upd";
    const char PROP_VALUE_GREEN_TEMPLATE[] PROGMEM = "g_tpl";
    const char PROP_VALUE_HOLD_COMMAND_TOPIC[] PROGMEM = "hold_cmd_t";
    const char PROP_VALUE_HOLD_STATE_TEMPLATE[] PROGMEM = "hold_stat_tpl";
    const char PROP_VALUE_HOLD_STATE_TOPIC[] PROGMEM = "hold_stat_t";
    const char PROP_VALUE_HS_COMMAND_TOPIC[] PROGMEM = "hs_cmd_t";
    const char PROP_VALUE_HS_STATE_TOPIC[] PROGMEM = "hs_stat_t";
    const char PROP_VALUE_HS_VALUE_TEMPLATE[] PROGMEM = "hs_val_tpl";
    const char PROP_VALUE_ICON[] PROGMEM = "ic";
    const char PROP_VALUE_INITIAL[] PROGMEM = "init";
    const char PROP_VALUE_JSON_ATTRIBUTES[] PROGMEM = "json_attr";
    const char PROP_VALUE_JSON_ATTRIBUTES_TOPIC[] PROGMEM = "json_attr_t";
    const char PROP_VALUE_JSON_ATTRIBUTES_TEMPLATE[] PROGMEM = "json_attr_tpl";
    const char PROP_VALUE_MAX_TEMP[] PROGMEM = "max_temp";
    const char PROP_VALUE_MIN_TEMP[] PROGMEM = "min_temp";
    const char PROP_VALUE_MODE_COMMAND_TOPIC[] PROGMEM = "mode_cmd_t";
    const char PROP_VALUE_MODE_STATE_TEMPLATE[] PROGMEM = "mode_stat_tpl";
    const char PROP_VALUE_MODE_STATE_TOPIC[] PROGMEM = "mode_stat_t";
    const char PROP_VALUE_NAME[] PROGMEM = "name";
    const char PROP_VALUE_OFF_DELAY[] PROGMEM = "off_dly";
    const char PROP_VALUE_ON_COMMAND_TYPE[] PROGMEM = "on_cmd_type";
    const char PROP_VALUE_OPTIMISTIC[] PROGMEM = "opt";
    const char PROP_VALUE_OSCILLATION_COMMAND_TOPIC[] PROGMEM = "osc_cmd_t";
    const char PROP_VALUE_OSCILLATION_STATE_TOPIC[] PROGMEM = "osc_stat_t";
    const char PROP_VALUE_OSCILLATION_VALUE_TEMPLATE[] PROGMEM = "osc_val_tpl";
    const char PROP_VALUE_PAYLOAD[] PROGMEM = "pl";
    const char PROP_VALUE_PAYLOAD_ARM_AWAY[] PROGMEM = "pl_arm_away";
    const char PROP_VALUE_PAYLOAD_ARM_HOME[] PROGMEM = "pl_arm_home";
    const char PROP_VALUE_PAYLOAD_ARM_NIGHT[] PROGMEM = "pl_arm_nite";
    const char PROP_VALUE_PAYLOAD_AVAILABLE[] PROGMEM = "pl_avail";
    const char PROP_VALUE_PAYLOAD_CLEAN_SPOT[] PROGMEM = "pl_cln_sp";
    const char PROP_VALUE_PAYLOAD_CLOSE[] PROGMEM = "pl_cls";
    const char PROP_VALUE_PAYLOAD_DISARM[] PROGMEM = "pl_disarm";
    const char PROP_VALUE_PAYLOAD_HIGH_SPEED[] PROGMEM = "pl_hi_spd";
    const char PROP_VALUE_PAYLOAD_HOME[] PROGMEM = "pl_home";
    const char PROP_VALUE_PAYLOAD_LOCK[] PROGMEM = "pl_lock";
    const char PROP_VALUE_PAYLOAD_LOCATE[] PROGMEM = "pl_loc";
    const char PROP_VALUE_PAYLOAD_LOW_SPEED[] PROGMEM = "pl_lo_spd";
    const char PROP_VALUE_PAYLOAD_MEDIUM_SPEED[] PROGMEM = "pl_med_spd";
    const char PROP_VALUE_PAYLOAD_NOT_AVAILABLE[] PROGMEM = "pl_not_avail";
    const char PROP_VALUE_PAYLOAD_NOT_HOME[] PROGMEM = "pl_not_home";
    const char PROP_VALUE_PAYLOAD_OFF[] PROGMEM = "pl_off";
    const char PROP_VALUE_PAYLOAD_OFF_SPEED[] PROGMEM = "pl_off_spd";
    const char PROP_VALUE_PAYLOAD_ON[] PROGMEM = "pl_on";
    const char PROP_VALUE_PAYLOAD_OPEN[] PROGMEM = "pl_open";
    const char PROP_VALUE_PAYLOAD_OSCILLATION_OFF[] PROGMEM = "pl_osc_off";
    const char PROP_VALUE_PAYLOAD_OSCILLATION_ON[] PROGMEM = "pl_osc_on";
    const char PROP_VALUE_PAYLOAD_PAUSE[] PROGMEM = "pl_paus";
    const char PROP_VALUE_PAYLOAD_STOP[] PROGMEM = "pl_stop";
    const char PROP_VALUE_PAYLOAD_START[] PROGMEM = "pl_strt";
    const char PROP_VALUE_PAYLOAD_START_PAUSE[] PROGMEM = "pl_stpa";
    const char PROP_VALUE_PAYLOAD_RETURN_TO_BASE[] PROGMEM = "pl_ret";
    const char PROP_VALUE_PAYLOAD_TURN_OFF[] PROGMEM = "pl_toff";
    const char PROP_VALUE_PAYLOAD_TURN_ON[] PROGMEM = "pl_ton";
    const char PROP_VALUE_PAYLOAD_UNLOCK[] PROGMEM = "pl_unlk";
    const char PROP_VALUE_POSITION_CLOSED[] PROGMEM = "pos_clsd";
    const char PROP_VALUE_POSITION_OPEN[] PROGMEM = "pos_open";
    const char PROP_VALUE_POWER_COMMAND_TOPIC[] PROGMEM = "pow_cmd_t";
    const char PROP_VALUE_POWER_STATE_TOPIC[] PROGMEM = "pow_stat_t";
    const char PROP_VALUE_POWER_STATE_TEMPLATE[] PROGMEM = "pow_stat_tpl";
    const char PROP_VALUE_RED_TEMPLATE[] PROGMEM = "r_tpl";
    const char PROP_VALUE_RETAIN[] PROGMEM = "ret";
    const char PROP_VALUE_RGB_COMMAND_TEMPLATE[] PROGMEM = "rgb_cmd_tpl";
    const char PROP_VALUE_RGB_COMMAND_TOPIC[] PROGMEM = "rgb_cmd_t";
    const char PROP_VALUE_RGB_STATE_TOPIC[] PROGMEM = "rgb_stat_t";
    const char PROP_VALUE_RGB_VALUE_TEMPLATE[] PROGMEM = "rgb_val_tpl";
    const char PROP_VALUE_SEND_COMMAND_TOPIC[] PROGMEM = "send_cmd_t";
    const char PROP_VALUE_SEND_IF_OFF[] PROGMEM = "send_if_off";
    const char PROP_VALUE_SET_FAN_SPEED_TOPIC[] PROGMEM = "set_fan_spd_t";
    const char PROP_VALUE_SET_POSITION_TEMPLATE[] PROGMEM = "set_pos_tpl";
    const char PROP_VALUE_SET_POSITION_TOPIC[] PROGMEM = "set_pos_t";
    const char PROP_VALUE_POSITION_TOPIC[] PROGMEM = "pos_t";
    const char PROP_VALUE_SPEED_COMMAND_TOPIC[] PROGMEM = "spd_cmd_t";
    const char PROP_VALUE_SPEED_STATE_TOPIC[] PROGMEM = "spd_stat_t";
    const char PROP_VALUE_SPEED_VALUE_TEMPLATE[] PROGMEM = "spd_val_tpl";
    const char PROP_VALUE_SPEEDS[] PROGMEM = "spds";
    const char PROP_VALUE_SOURCE_TYPE[] PROGMEM = "src_type";
    const char PROP_VALUE_STATE_CLOSED[] PROGMEM = "stat_clsd";
    const char PROP_VALUE_STATE_CLOSING[] PROGMEM = "stat_closing";
    const char PROP_VALUE_STATE_OFF[] PROGMEM = "stat_off";
    const char PROP_VALUE_STATE_ON[] PROGMEM = "stat_on";
    const char PROP_VALUE_STATE_OPEN[] PROGMEM = "stat_open";
    const char PROP_VALUE_STATE_OPENING[] PROGMEM = "stat_opening";
    const char PROP_VALUE_STATE_LOCKED[] PROGMEM = "stat_locked";
    const char PROP_VALUE_STATE_UNLOCKED[] PROGMEM = "stat_unlocked";
    const char PROP_VALUE_STATE_TOPIC[] PROGMEM = "stat_t";
    const char PROP_VALUE_STATE_TEMPLATE[] PROGMEM = "stat_tpl";
    const char PROP_VALUE_STATE_VALUE_TEMPLATE[] PROGMEM = "stat_val_tpl";
    const char PROP_VALUE_SUBTYPE[] PROGMEM = "stype";
    const char PROP_VALUE_SUPPORTED_FEATURES[] PROGMEM = "sup_feat";
    const char PROP_VALUE_SWING_MODE_COMMAND_TOPIC[] PROGMEM = "swing_mode_cmd_t";
    const char PROP_VALUE_SWING_MODE_STATE_TEMPLATE[] PROGMEM = "swing_mode_stat_tpl";
    const char PROP_VALUE_SWING_MODE_STATE_TOPIC[] PROGMEM = "swing_mode_stat_t";
    const char PROP_VALUE_TEMPERATURE_COMMAND_TOPIC[] PROGMEM = "temp_cmd_t";
    const char PROP_VALUE_TEMPERATURE_HIGH_COMMAND_TOPIC[] PROGMEM = "temp_hi_cmd_t";
    const char PROP_VALUE_TEMPERATURE_HIGH_STATE_TEMPLATE[] PROGMEM = "temp_hi_stat_tpl";
    const char PROP_VALUE_TEMPERATURE_HIGH_STATE_TOPIC[] PROGMEM = "temp_hi_stat_t";
    const char PROP_VALUE_TEMPERATURE_LOW_COMMAND_TOPIC[] PROGMEM = "temp_lo_cmd_t";
    const char PROP_VALUE_TEMPERATURE_LOW_STATE_TEMPLATE[] PROGMEM = "temp_lo_stat_tpl";
    const char PROP_VALUE_TEMPERATURE_LOW_STATE_TOPIC[] PROGMEM = "temp_lo_stat_t";
    const char PROP_VALUE_TEMPERATURE_STATE_TEMPLATE[] PROGMEM = "temp_stat_tpl";
    const char PROP_VALUE_TEMPERATURE_STATE_TOPIC[] PROGMEM = "temp_stat_t";
    const char PROP_VALUE_TILT_CLOSED_VALUE[] PROGMEM = "tilt_clsd_val";
    const char PROP_VALUE_TILT_COMMAND_TOPIC[] PROGMEM = "tilt_cmd_t";
    const char PROP_VALUE_TILT_INVERT_STATE[] PROGMEM = "tilt_inv_stat";
    const char PROP_VALUE_TILT_MAX[] PROGMEM = "tilt_max";
    const char PROP_VALUE_TILT_MIN[] PROGMEM = "tilt_min";
    const char PROP_VALUE_TILT_OPENED_VALUE[] PROGMEM = "tilt_opnd_val";
    const char PROP_VALUE_TILT_OPTIMISTIC[] PROGMEM = "tilt_opt";
    const char PROP_VALUE_TILT_STATUS_TOPIC[] PROGMEM = "tilt_status_t";
    const char PROP_VALUE_TILT_STATUS_TEMPLATE[] PROGMEM = "tilt_status_tpl";
    const char PROP_VALUE_TOPIC_TOPIC[] PROGMEM = "t";
    const char PROP_VALUE_UNIQUE_ID[] PROGMEM = "uniq_id";
    const char PROP_VALUE_UNIT_OF_MEASUREMENT[] PROGMEM = "unit_of_meas";
    const char PROP_VALUE_VALUE_TEMPLATE[] PROGMEM = "val_tpl";
    const char PROP_VALUE_WHITE_VALUE_COMMAND_TOPIC[] PROGMEM = "whit_val_cmd_t";
    const char PROP_VALUE_WHITE_VALUE_SCALE[] PROGMEM = "whit_val_scl";
    const char PROP_VALUE_WHITE_VALUE_STATE_TOPIC[] PROGMEM = "whit_val_stat_t";
    const char PROP_VALUE_WHITE_VALUE_TEMPLATE[] PROGMEM = "whit_val_tpl";
    const char PROP_VALUE_XY_COMMAND_TOPIC[] PROGMEM = "xy_cmd_t";
    const char PROP_VALUE_XY_STATE_TOPIC[] PROGMEM = "xy_stat_t";
    const char PROP_VALUE_XY_VALUE_TEMPLATE[] PROGMEM = "xy_val_tpl";
    const char PROP_VALUE_TYPE[] PROGMEM = "type";
    const char PROP_VALUE_STYPE[] PROGMEM = "stype";
    const char PROP_VALUE_STATE_CLASS[] PROGMEM = "state_class";
    const char PROP_VALUE_ENTITY_CATEGORY[] PROGMEM = "entity_category";

    const static char DEFAULT_VALUE_EMPTY[] PROGMEM = "";
    const static char DEFAULT_VALUE_ROOT_TOPIC[] PROGMEM = "";
    const static char DEFAULT_VALUE_ACTION_TOPIC[] PROGMEM = "~/act";
    const static char DEFAULT_VALUE_ACTION_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_AUTOMATION_TYPE[] PROGMEM = "";
    const static char DEFAULT_VALUE_AUX_COMMAND_TOPIC[] PROGMEM = "~/auxcmd";
    const static char DEFAULT_VALUE_AUX_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_AUX_STATE_TOPIC[] PROGMEM = "~/auxstat";
    const static char DEFAULT_VALUE_AVAILABILITY_TOPIC[] PROGMEM = "~/auxavty";
    const static char DEFAULT_VALUE_AWAY_MODE_COMMAND_TOPIC[] PROGMEM = "~/awycmd";
    const static char DEFAULT_VALUE_AWAY_MODE_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_AWAY_MODE_STATE_TOPIC[] PROGMEM = "~/awystat";
    const static char DEFAULT_VALUE_BLUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_BRIGHTNESS_COMMAND_TOPIC[] PROGMEM = "~/bricmd";
    const static char DEFAULT_VALUE_BRIGHTNESS_SCALE[] PROGMEM = "";
    const static char DEFAULT_VALUE_BRIGHTNESS_STATE_TOPIC[] PROGMEM = "~/bristat";
    const static char DEFAULT_VALUE_BRIGHTNESS_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_BRIGHTNESS_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_COLOR_TEMP_COMMAND_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_BATTERY_LEVEL_TOPIC[] PROGMEM = "~/batlev";
    const static char DEFAULT_VALUE_BATTERY_LEVEL_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_CHARGING_TOPIC[] PROGMEM = "~/chrg";
    const static char DEFAULT_VALUE_CHARGING_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_COLOR_TEMP_COMMAND_TOPIC[] PROGMEM = "~/clrtmp";
    const static char DEFAULT_VALUE_COLOR_TEMP_STATE_TOPIC[] PROGMEM = "~/clrtmpstat";
    const static char DEFAULT_VALUE_COLOR_TEMP_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_COLOR_TEMP_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_CLEANING_TOPIC[] PROGMEM = "~/cln";
    const static char DEFAULT_VALUE_CLEANING_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_COMMAND_OFF_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_COMMAND_ON_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_COMMAND_TOPIC[] PROGMEM = "~/cmd";
    const static char DEFAULT_VALUE_COMMAND_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_CODE_ARM_REQUIRED[] PROGMEM = "";
    const static char DEFAULT_VALUE_CODE_DISARM_REQUIRED[] PROGMEM = "";
    const static char DEFAULT_VALUE_CURRENT_TEMPERATURE_TOPIC[] PROGMEM = "~/curtmp";
    const static char DEFAULT_VALUE_CURRENT_TEMPERATURE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE_CONNECTION[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE_IDENTIFIER[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE_MANUFACTURER[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE_MODEL[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE_RELEASE[] PROGMEM = "";
    const static char DEFAULT_VALUE_DEVICE_CLASS[] PROGMEM = "";
    const static char DEFAULT_VALUE_DOCKED_TOPIC[] PROGMEM = "~/dock";
    const static char DEFAULT_VALUE_DOCKED_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_ERROR_TOPIC[] PROGMEM = "~/err";
    const static char DEFAULT_VALUE_ERROR_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_FAN_SPEED_TOPIC[] PROGMEM = "~/fanspd";
    const static char DEFAULT_VALUE_FAN_SPEED_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_FAN_SPEED_LIST[] PROGMEM = "";
    const static char DEFAULT_VALUE_FLASH_TIME_LONG[] PROGMEM = "";
    const static char DEFAULT_VALUE_FLASH_TIME_SHORT[] PROGMEM = "";
    const static char DEFAULT_VALUE_EFFECT_COMMAND_TOPIC[] PROGMEM = "~/fxcmd";
    const static char DEFAULT_VALUE_EFFECT_LIST[] PROGMEM = "";
    const static char DEFAULT_VALUE_EFFECT_STATE_TOPIC[] PROGMEM = "~/fxstat";
    const static char DEFAULT_VALUE_EFFECT_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_EFFECT_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_EXPIRE_AFTER[] PROGMEM = "";
    const static char DEFAULT_VALUE_FAN_MODE_COMMAND_TOPIC[] PROGMEM = "~/fanmd";
    const static char DEFAULT_VALUE_FAN_MODE_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_FAN_MODE_STATE_TOPIC[] PROGMEM = "~/fanstat";
    const static char DEFAULT_VALUE_FORCE_UPDATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_GREEN_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_HOLD_COMMAND_TOPIC[] PROGMEM = "~/hcmd";
    const static char DEFAULT_VALUE_HOLD_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_HOLD_STATE_TOPIC[] PROGMEM = "~/hstat";
    const static char DEFAULT_VALUE_HS_COMMAND_TOPIC[] PROGMEM = "~/hscmd";
    const static char DEFAULT_VALUE_HS_STATE_TOPIC[] PROGMEM = "~/hsstat";
    const static char DEFAULT_VALUE_HS_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_ICON[] PROGMEM = "";
    const static char DEFAULT_VALUE_INITIAL[] PROGMEM = "";
    const static char DEFAULT_VALUE_JSON_ATTRIBUTES[] PROGMEM = "";
    const static char DEFAULT_VALUE_JSON_ATTRIBUTES_TOPIC[] PROGMEM = "~/jsonatt";
    const static char DEFAULT_VALUE_JSON_ATTRIBUTES_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_MAX_TEMP[] PROGMEM = "";
    const static char DEFAULT_VALUE_MIN_TEMP[] PROGMEM = "";
    const static char DEFAULT_VALUE_MODE_COMMAND_TOPIC[] PROGMEM = "~/mdcmd";
    const static char DEFAULT_VALUE_MODE_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_MODE_STATE_TOPIC[] PROGMEM = "~/mdstat";
    const static char DEFAULT_VALUE_NAME[] PROGMEM = "";
    const static char DEFAULT_VALUE_OFF_DELAY[] PROGMEM = "";
    const static char DEFAULT_VALUE_ON_COMMAND_TYPE[] PROGMEM = "";
    const static char DEFAULT_VALUE_OPTIMISTIC[] PROGMEM = "~/optmc";
    const static char DEFAULT_VALUE_OSCILLATION_COMMAND_TOPIC[] PROGMEM = "~/osccmd";
    const static char DEFAULT_VALUE_OSCILLATION_STATE_TOPIC[] PROGMEM = "~/oscstat";
    const static char DEFAULT_VALUE_OSCILLATION_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_ARM_AWAY[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_ARM_HOME[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_ARM_NIGHT[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_AVAILABLE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_CLEAN_SPOT[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_CLOSE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_DISARM[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_HIGH_SPEED[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_HOME[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_LOCK[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_LOCATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_LOW_SPEED[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_MEDIUM_SPEED[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_NOT_AVAILABLE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_NOT_HOME[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_OFF[] PROGMEM = "OFF";
    const static char DEFAULT_VALUE_PAYLOAD_OFF_SPEED[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_ON[] PROGMEM = "ON";
    const static char DEFAULT_VALUE_PAYLOAD_OPEN[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_OSCILLATION_OFF[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_OSCILLATION_ON[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_PAUSE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_STOP[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_START[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_START_PAUSE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_RETURN_TO_BASE[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_TURN_OFF[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_TURN_ON[] PROGMEM = "";
    const static char DEFAULT_VALUE_PAYLOAD_UNLOCK[] PROGMEM = "";
    const static char DEFAULT_VALUE_POSITION_CLOSED[] PROGMEM = "";
    const static char DEFAULT_VALUE_POSITION_OPEN[] PROGMEM = "";
    const static char DEFAULT_VALUE_POWER_COMMAND_TOPIC[] PROGMEM = "~/pcmd";
    const static char DEFAULT_VALUE_POWER_STATE_TOPIC[] PROGMEM = "~/pstat";
    const static char DEFAULT_VALUE_POWER_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_RED_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_RETAIN[] PROGMEM = "";
    const static char DEFAULT_VALUE_RGB_COMMAND_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_RGB_COMMAND_TOPIC[] PROGMEM = "~/rgbcmd";
    const static char DEFAULT_VALUE_RGB_STATE_TOPIC[] PROGMEM = "~/rgbstat";
    const static char DEFAULT_VALUE_RGB_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_SEND_COMMAND_TOPIC[] PROGMEM = "~/sndcmd";
    const static char DEFAULT_VALUE_SEND_IF_OFF[] PROGMEM = "";
    const static char DEFAULT_VALUE_SET_FAN_SPEED_TOPIC[] PROGMEM = "~/fanspdcmd";
    const static char DEFAULT_VALUE_SET_POSITION_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_SET_POSITION_TOPIC[] PROGMEM = "~/poscmd";
    const static char DEFAULT_VALUE_POSITION_TOPIC[] PROGMEM = "~/pos";
    const static char DEFAULT_VALUE_SPEED_COMMAND_TOPIC[] PROGMEM = "~/spdcmd";
    const static char DEFAULT_VALUE_SPEED_STATE_TOPIC[] PROGMEM = "~/spdstat";
    const static char DEFAULT_VALUE_SPEED_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_SPEEDS[] PROGMEM = "";
    const static char DEFAULT_VALUE_SOURCE_TYPE[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_CLOSED[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_CLOSING[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_OFF[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_ON[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_OPEN[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_OPENING[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_LOCKED[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_UNLOCKED[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_TOPIC[] PROGMEM = "~/stat";
    const static char DEFAULT_VALUE_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_SUBTYPE[] PROGMEM = "";
    const static char DEFAULT_VALUE_SUPPORTED_FEATURES[] PROGMEM = "";
    const static char DEFAULT_VALUE_SWING_MODE_COMMAND_TOPIC[] PROGMEM = "~/swgcmd";
    const static char DEFAULT_VALUE_SWING_MODE_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_SWING_MODE_STATE_TOPIC[] PROGMEM = "~/swgstat";
    const static char DEFAULT_VALUE_TEMPERATURE_COMMAND_TOPIC[] PROGMEM = "~/tcmd";
    const static char DEFAULT_VALUE_TEMPERATURE_HIGH_COMMAND_TOPIC[] PROGMEM = "~/thcmd";
    const static char DEFAULT_VALUE_TEMPERATURE_HIGH_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TEMPERATURE_HIGH_STATE_TOPIC[] PROGMEM = "~/thstat";
    const static char DEFAULT_VALUE_TEMPERATURE_LOW_COMMAND_TOPIC[] PROGMEM = "~/tlcmd";
    const static char DEFAULT_VALUE_TEMPERATURE_LOW_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TEMPERATURE_LOW_STATE_TOPIC[] PROGMEM = "~/tlstat";
    const static char DEFAULT_VALUE_TEMPERATURE_STATE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TEMPERATURE_STATE_TOPIC[] PROGMEM = "~/tstat";
    const static char DEFAULT_VALUE_TILT_CLOSED_VALUE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TILT_COMMAND_TOPIC[] PROGMEM = "~/tltcmd";
    const static char DEFAULT_VALUE_TILT_INVERT_STATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TILT_MAX[] PROGMEM = "";
    const static char DEFAULT_VALUE_TILT_MIN[] PROGMEM = "";
    const static char DEFAULT_VALUE_TILT_OPENED_VALUE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TILT_OPTIMISTIC[] PROGMEM = "";
    const static char DEFAULT_VALUE_TILT_STATUS_TOPIC[] PROGMEM = "~/tltstat";
    const static char DEFAULT_VALUE_TILT_STATUS_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TOPIC_TOPIC[] PROGMEM = "~/tpc";
    const static char DEFAULT_VALUE_UNIQUE_ID[] PROGMEM = "";
    const static char DEFAULT_VALUE_UNIT_OF_MEASUREMENT[] PROGMEM = "";
    const static char DEFAULT_VALUE_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_WHITE_VALUE_COMMAND_TOPIC[] PROGMEM = "~/wvalcmd";
    const static char DEFAULT_VALUE_WHITE_VALUE_SCALE[] PROGMEM = "";
    const static char DEFAULT_VALUE_WHITE_VALUE_STATE_TOPIC[] PROGMEM = "~/wvalstat";
    const static char DEFAULT_VALUE_WHITE_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_XY_COMMAND_TOPIC[] PROGMEM = "~/xycmd";
    const static char DEFAULT_VALUE_XY_STATE_TOPIC[] PROGMEM = "~/xystat";
    const static char DEFAULT_VALUE_XY_VALUE_TEMPLATE[] PROGMEM = "";
    const static char DEFAULT_VALUE_TYPE[] PROGMEM = "";
    const static char DEFAULT_VALUE_STYPE[] PROGMEM = "";
    const static char DEFAULT_VALUE_STATE_CLASS[] PROGMEM = "";

    // -------------------------------------------------------------------------
    // 4. Définition des Tableaux de Pointeurs (Ce qui manquait !)
    // -------------------------------------------------------------------------

    // Ordre strictement identique à l'enum HAComponentPropertyKey dans le .hpp
    PGM_P DiscoveryMessageKeyLabel[] PROGMEM = {
        PROP_VALUE_ROOT_TOPIC,
        PROP_VALUE_ACTION_TOPIC,
        PROP_VALUE_ACTION_TEMPLATE,
        PROP_VALUE_AUTOMATION_TYPE,
        PROP_VALUE_AUX_COMMAND_TOPIC,
        PROP_VALUE_AUX_STATE_TEMPLATE,
        PROP_VALUE_AUX_STATE_TOPIC,
        PROP_VALUE_AVAILABILITY_TOPIC,
        PROP_VALUE_AWAY_MODE_COMMAND_TOPIC,
        PROP_VALUE_AWAY_MODE_STATE_TEMPLATE,
        PROP_VALUE_AWAY_MODE_STATE_TOPIC,
        PROP_VALUE_BLUE_TEMPLATE,
        PROP_VALUE_BRIGHTNESS_COMMAND_TOPIC,
        PROP_VALUE_BRIGHTNESS_SCALE,
        PROP_VALUE_BRIGHTNESS_STATE_TOPIC,
        PROP_VALUE_BRIGHTNESS_TEMPLATE,
        PROP_VALUE_BRIGHTNESS_VALUE_TEMPLATE,
        PROP_VALUE_COLOR_TEMP_COMMAND_TEMPLATE,
        PROP_VALUE_BATTERY_LEVEL_TOPIC,
        PROP_VALUE_BATTERY_LEVEL_TEMPLATE,
        PROP_VALUE_CHARGING_TOPIC,
        PROP_VALUE_CHARGING_TEMPLATE,
        PROP_VALUE_COLOR_TEMP_COMMAND_TOPIC,
        PROP_VALUE_COLOR_TEMP_STATE_TOPIC,
        PROP_VALUE_COLOR_TEMP_TEMPLATE,
        PROP_VALUE_COLOR_TEMP_VALUE_TEMPLATE,
        PROP_VALUE_CLEANING_TOPIC,
        PROP_VALUE_CLEANING_TEMPLATE,
        PROP_VALUE_COMMAND_OFF_TEMPLATE,
        PROP_VALUE_COMMAND_ON_TEMPLATE,
        PROP_VALUE_COMMAND_TOPIC,
        PROP_VALUE_COMMAND_TEMPLATE,
        PROP_VALUE_CODE_ARM_REQUIRED,
        PROP_VALUE_CODE_DISARM_REQUIRED,
        PROP_VALUE_CURRENT_TEMPERATURE_TOPIC,
        PROP_VALUE_CURRENT_TEMPERATURE_TEMPLATE,
        PROP_VALUE_DEVICE,
        PROP_VALUE_DEVICE_CONNECTION,
        PROP_VALUE_DEVICE_IDENTIFIER,
        PROP_VALUE_DEVICE_MANUFACTURER,
        PROP_VALUE_DEVICE_MODEL,
        PROP_VALUE_DEVICE_RELEASE,
        PROP_VALUE_DEVICE_CLASS,
        PROP_VALUE_DOCKED_TOPIC,
        PROP_VALUE_DOCKED_TEMPLATE,
        PROP_VALUE_ERROR_TOPIC,
        PROP_VALUE_ERROR_TEMPLATE,
        PROP_VALUE_FAN_SPEED_TOPIC,
        PROP_VALUE_FAN_SPEED_TEMPLATE,
        PROP_VALUE_FAN_SPEED_LIST,
        PROP_VALUE_FLASH_TIME_LONG,
        PROP_VALUE_FLASH_TIME_SHORT,
        PROP_VALUE_EFFECT_COMMAND_TOPIC,
        PROP_VALUE_EFFECT_LIST,
        PROP_VALUE_EFFECT_STATE_TOPIC,
        PROP_VALUE_EFFECT_TEMPLATE,
        PROP_VALUE_EFFECT_VALUE_TEMPLATE,
        PROP_VALUE_EXPIRE_AFTER,
        PROP_VALUE_FAN_MODE_COMMAND_TOPIC,
        PROP_VALUE_FAN_MODE_STATE_TEMPLATE,
        PROP_VALUE_FAN_MODE_STATE_TOPIC,
        PROP_VALUE_FORCE_UPDATE,
        PROP_VALUE_GREEN_TEMPLATE,
        PROP_VALUE_HOLD_COMMAND_TOPIC,
        PROP_VALUE_HOLD_STATE_TEMPLATE,
        PROP_VALUE_HOLD_STATE_TOPIC,
        PROP_VALUE_HS_COMMAND_TOPIC,
        PROP_VALUE_HS_STATE_TOPIC,
        PROP_VALUE_HS_VALUE_TEMPLATE,
        PROP_VALUE_ICON,
        PROP_VALUE_INITIAL,
        PROP_VALUE_JSON_ATTRIBUTES,
        PROP_VALUE_JSON_ATTRIBUTES_TOPIC,
        PROP_VALUE_JSON_ATTRIBUTES_TEMPLATE,
        PROP_VALUE_MAX_TEMP,
        PROP_VALUE_MIN_TEMP,
        PROP_VALUE_MODE_COMMAND_TOPIC,
        PROP_VALUE_MODE_STATE_TEMPLATE,
        PROP_VALUE_MODE_STATE_TOPIC,
        PROP_VALUE_NAME,
        PROP_VALUE_OFF_DELAY,
        PROP_VALUE_ON_COMMAND_TYPE,
        PROP_VALUE_OPTIMISTIC,
        PROP_VALUE_OSCILLATION_COMMAND_TOPIC,
        PROP_VALUE_OSCILLATION_STATE_TOPIC,
        PROP_VALUE_OSCILLATION_VALUE_TEMPLATE,
        PROP_VALUE_PAYLOAD,
        PROP_VALUE_PAYLOAD_ARM_AWAY,
        PROP_VALUE_PAYLOAD_ARM_HOME,
        PROP_VALUE_PAYLOAD_ARM_NIGHT,
        PROP_VALUE_PAYLOAD_AVAILABLE,
        PROP_VALUE_PAYLOAD_CLEAN_SPOT,
        PROP_VALUE_PAYLOAD_CLOSE,
        PROP_VALUE_PAYLOAD_DISARM,
        PROP_VALUE_PAYLOAD_HIGH_SPEED,
        PROP_VALUE_PAYLOAD_HOME,
        PROP_VALUE_PAYLOAD_LOCK,
        PROP_VALUE_PAYLOAD_LOCATE,
        PROP_VALUE_PAYLOAD_LOW_SPEED,
        PROP_VALUE_PAYLOAD_MEDIUM_SPEED,
        PROP_VALUE_PAYLOAD_NOT_AVAILABLE,
        PROP_VALUE_PAYLOAD_NOT_HOME,
        PROP_VALUE_PAYLOAD_OFF,
        PROP_VALUE_PAYLOAD_OFF_SPEED,
        PROP_VALUE_PAYLOAD_ON,
        PROP_VALUE_PAYLOAD_OPEN,
        PROP_VALUE_PAYLOAD_OSCILLATION_OFF,
        PROP_VALUE_PAYLOAD_OSCILLATION_ON,
        PROP_VALUE_PAYLOAD_PAUSE,
        PROP_VALUE_PAYLOAD_STOP,
        PROP_VALUE_PAYLOAD_START,
        PROP_VALUE_PAYLOAD_START_PAUSE,
        PROP_VALUE_PAYLOAD_RETURN_TO_BASE,
        PROP_VALUE_PAYLOAD_TURN_OFF,
        PROP_VALUE_PAYLOAD_TURN_ON,
        PROP_VALUE_PAYLOAD_UNLOCK,
        PROP_VALUE_POSITION_CLOSED,
        PROP_VALUE_POSITION_OPEN,
        PROP_VALUE_POWER_COMMAND_TOPIC,
        PROP_VALUE_POWER_STATE_TOPIC,
        PROP_VALUE_POWER_STATE_TEMPLATE,
        PROP_VALUE_RED_TEMPLATE,
        PROP_VALUE_RETAIN,
        PROP_VALUE_RGB_COMMAND_TEMPLATE,
        PROP_VALUE_RGB_COMMAND_TOPIC,
        PROP_VALUE_RGB_STATE_TOPIC,
        PROP_VALUE_RGB_VALUE_TEMPLATE,
        PROP_VALUE_SEND_COMMAND_TOPIC,
        PROP_VALUE_SEND_IF_OFF,
        PROP_VALUE_SET_FAN_SPEED_TOPIC,
        PROP_VALUE_SET_POSITION_TEMPLATE,
        PROP_VALUE_SET_POSITION_TOPIC,
        PROP_VALUE_POSITION_TOPIC,
        PROP_VALUE_SPEED_COMMAND_TOPIC,
        PROP_VALUE_SPEED_STATE_TOPIC,
        PROP_VALUE_SPEED_VALUE_TEMPLATE,
        PROP_VALUE_SPEEDS,
        PROP_VALUE_SOURCE_TYPE,
        PROP_VALUE_STATE_CLOSED,
        PROP_VALUE_STATE_CLOSING,
        PROP_VALUE_STATE_OFF,
        PROP_VALUE_STATE_ON,
        PROP_VALUE_STATE_OPEN,
        PROP_VALUE_STATE_OPENING,
        PROP_VALUE_STATE_LOCKED,
        PROP_VALUE_STATE_UNLOCKED,
        PROP_VALUE_STATE_TOPIC,
        PROP_VALUE_STATE_TEMPLATE,
        PROP_VALUE_STATE_VALUE_TEMPLATE,
        PROP_VALUE_SUBTYPE,
        PROP_VALUE_SUPPORTED_FEATURES,
        PROP_VALUE_SWING_MODE_COMMAND_TOPIC,
        PROP_VALUE_SWING_MODE_STATE_TEMPLATE,
        PROP_VALUE_SWING_MODE_STATE_TOPIC,
        PROP_VALUE_TEMPERATURE_COMMAND_TOPIC,
        PROP_VALUE_TEMPERATURE_HIGH_COMMAND_TOPIC,
        PROP_VALUE_TEMPERATURE_HIGH_STATE_TEMPLATE,
        PROP_VALUE_TEMPERATURE_HIGH_STATE_TOPIC,
        PROP_VALUE_TEMPERATURE_LOW_COMMAND_TOPIC,
        PROP_VALUE_TEMPERATURE_LOW_STATE_TEMPLATE,
        PROP_VALUE_TEMPERATURE_LOW_STATE_TOPIC,
        PROP_VALUE_TEMPERATURE_STATE_TEMPLATE,
        PROP_VALUE_TEMPERATURE_STATE_TOPIC,
        PROP_VALUE_TILT_CLOSED_VALUE,
        PROP_VALUE_TILT_COMMAND_TOPIC,
        PROP_VALUE_TILT_INVERT_STATE,
        PROP_VALUE_TILT_MAX,
        PROP_VALUE_TILT_MIN,
        PROP_VALUE_TILT_OPENED_VALUE,
        PROP_VALUE_TILT_OPTIMISTIC,
        PROP_VALUE_TILT_STATUS_TOPIC,
        PROP_VALUE_TILT_STATUS_TEMPLATE,
        PROP_VALUE_TOPIC_TOPIC,
        PROP_VALUE_UNIQUE_ID,
        PROP_VALUE_UNIT_OF_MEASUREMENT,
        PROP_VALUE_VALUE_TEMPLATE,
        PROP_VALUE_WHITE_VALUE_COMMAND_TOPIC,
        PROP_VALUE_WHITE_VALUE_SCALE,
        PROP_VALUE_WHITE_VALUE_STATE_TOPIC,
        PROP_VALUE_WHITE_VALUE_TEMPLATE,
        PROP_VALUE_XY_COMMAND_TOPIC,
        PROP_VALUE_XY_STATE_TOPIC,
        PROP_VALUE_XY_VALUE_TEMPLATE,
        PROP_VALUE_TYPE,
        PROP_VALUE_STYPE,
        PROP_VALUE_STATE_CLASS,
        PROP_VALUE_ENTITY_CATEGORY,
    };

    PGM_P PropertyDefaultValue[] PROGMEM = {
        DEFAULT_VALUE_ROOT_TOPIC,
        DEFAULT_VALUE_ACTION_TOPIC,
        DEFAULT_VALUE_ACTION_TEMPLATE,
        DEFAULT_VALUE_AUTOMATION_TYPE,
        DEFAULT_VALUE_AUX_COMMAND_TOPIC,
        DEFAULT_VALUE_AUX_STATE_TEMPLATE,
        DEFAULT_VALUE_AUX_STATE_TOPIC,
        DEFAULT_VALUE_AVAILABILITY_TOPIC,
        DEFAULT_VALUE_AWAY_MODE_COMMAND_TOPIC,
        DEFAULT_VALUE_AWAY_MODE_STATE_TEMPLATE,
        DEFAULT_VALUE_AWAY_MODE_STATE_TOPIC,
        DEFAULT_VALUE_BLUE_TEMPLATE,
        DEFAULT_VALUE_BRIGHTNESS_COMMAND_TOPIC,
        DEFAULT_VALUE_BRIGHTNESS_SCALE,
        DEFAULT_VALUE_BRIGHTNESS_STATE_TOPIC,
        DEFAULT_VALUE_BRIGHTNESS_TEMPLATE,
        DEFAULT_VALUE_BRIGHTNESS_VALUE_TEMPLATE,
        DEFAULT_VALUE_COLOR_TEMP_COMMAND_TEMPLATE,
        DEFAULT_VALUE_BATTERY_LEVEL_TOPIC,
        DEFAULT_VALUE_BATTERY_LEVEL_TEMPLATE,
        DEFAULT_VALUE_CHARGING_TOPIC,
        DEFAULT_VALUE_CHARGING_TEMPLATE,
        DEFAULT_VALUE_COLOR_TEMP_COMMAND_TOPIC,
        DEFAULT_VALUE_COLOR_TEMP_STATE_TOPIC,
        DEFAULT_VALUE_COLOR_TEMP_TEMPLATE,
        DEFAULT_VALUE_COLOR_TEMP_VALUE_TEMPLATE,
        DEFAULT_VALUE_CLEANING_TOPIC,
        DEFAULT_VALUE_CLEANING_TEMPLATE,
        DEFAULT_VALUE_COMMAND_OFF_TEMPLATE,
        DEFAULT_VALUE_COMMAND_ON_TEMPLATE,
        DEFAULT_VALUE_COMMAND_TOPIC,
        DEFAULT_VALUE_COMMAND_TEMPLATE,
        DEFAULT_VALUE_CODE_ARM_REQUIRED,
        DEFAULT_VALUE_CODE_DISARM_REQUIRED,
        DEFAULT_VALUE_CURRENT_TEMPERATURE_TOPIC,
        DEFAULT_VALUE_CURRENT_TEMPERATURE_TEMPLATE,
        DEFAULT_VALUE_DEVICE,
        DEFAULT_VALUE_DEVICE_CONNECTION,
        DEFAULT_VALUE_DEVICE_IDENTIFIER,
        DEFAULT_VALUE_DEVICE_MANUFACTURER,
        DEFAULT_VALUE_DEVICE_MODEL,
        DEFAULT_VALUE_DEVICE_RELEASE,
        DEFAULT_VALUE_DEVICE_CLASS,
        DEFAULT_VALUE_DOCKED_TOPIC,
        DEFAULT_VALUE_DOCKED_TEMPLATE,
        DEFAULT_VALUE_ERROR_TOPIC,
        DEFAULT_VALUE_ERROR_TEMPLATE,
        DEFAULT_VALUE_FAN_SPEED_TOPIC,
        DEFAULT_VALUE_FAN_SPEED_TEMPLATE,
        DEFAULT_VALUE_FAN_SPEED_LIST,
        DEFAULT_VALUE_FLASH_TIME_LONG,
        DEFAULT_VALUE_FLASH_TIME_SHORT,
        DEFAULT_VALUE_EFFECT_COMMAND_TOPIC,
        DEFAULT_VALUE_EFFECT_LIST,
        DEFAULT_VALUE_EFFECT_STATE_TOPIC,
        DEFAULT_VALUE_EFFECT_TEMPLATE,
        DEFAULT_VALUE_EFFECT_VALUE_TEMPLATE,
        DEFAULT_VALUE_EXPIRE_AFTER,
        DEFAULT_VALUE_FAN_MODE_COMMAND_TOPIC,
        DEFAULT_VALUE_FAN_MODE_STATE_TEMPLATE,
        DEFAULT_VALUE_FAN_MODE_STATE_TOPIC,
        DEFAULT_VALUE_FORCE_UPDATE,
        DEFAULT_VALUE_GREEN_TEMPLATE,
        DEFAULT_VALUE_HOLD_COMMAND_TOPIC,
        DEFAULT_VALUE_HOLD_STATE_TEMPLATE,
        DEFAULT_VALUE_HOLD_STATE_TOPIC,
        DEFAULT_VALUE_HS_COMMAND_TOPIC,
        DEFAULT_VALUE_HS_STATE_TOPIC,
        DEFAULT_VALUE_HS_VALUE_TEMPLATE,
        DEFAULT_VALUE_ICON,
        DEFAULT_VALUE_INITIAL,
        DEFAULT_VALUE_JSON_ATTRIBUTES,
        DEFAULT_VALUE_JSON_ATTRIBUTES_TOPIC,
        DEFAULT_VALUE_JSON_ATTRIBUTES_TEMPLATE,
        DEFAULT_VALUE_MAX_TEMP,
        DEFAULT_VALUE_MIN_TEMP,
        DEFAULT_VALUE_MODE_COMMAND_TOPIC,
        DEFAULT_VALUE_MODE_STATE_TEMPLATE,
        DEFAULT_VALUE_MODE_STATE_TOPIC,
        DEFAULT_VALUE_NAME,
        DEFAULT_VALUE_OFF_DELAY,
        DEFAULT_VALUE_ON_COMMAND_TYPE,
        DEFAULT_VALUE_OPTIMISTIC,
        DEFAULT_VALUE_OSCILLATION_COMMAND_TOPIC,
        DEFAULT_VALUE_OSCILLATION_STATE_TOPIC,
        DEFAULT_VALUE_OSCILLATION_VALUE_TEMPLATE,
        DEFAULT_VALUE_PAYLOAD,
        DEFAULT_VALUE_PAYLOAD_ARM_AWAY,
        DEFAULT_VALUE_PAYLOAD_ARM_HOME,
        DEFAULT_VALUE_PAYLOAD_ARM_NIGHT,
        DEFAULT_VALUE_PAYLOAD_AVAILABLE,
        DEFAULT_VALUE_PAYLOAD_CLEAN_SPOT,
        DEFAULT_VALUE_PAYLOAD_CLOSE,
        DEFAULT_VALUE_PAYLOAD_DISARM,
        DEFAULT_VALUE_PAYLOAD_HIGH_SPEED,
        DEFAULT_VALUE_PAYLOAD_HOME,
        DEFAULT_VALUE_PAYLOAD_LOCK,
        DEFAULT_VALUE_PAYLOAD_LOCATE,
        DEFAULT_VALUE_PAYLOAD_LOW_SPEED,
        DEFAULT_VALUE_PAYLOAD_MEDIUM_SPEED,
        DEFAULT_VALUE_PAYLOAD_NOT_AVAILABLE,
        DEFAULT_VALUE_PAYLOAD_NOT_HOME,
        DEFAULT_VALUE_PAYLOAD_OFF,
        DEFAULT_VALUE_PAYLOAD_OFF_SPEED,
        DEFAULT_VALUE_PAYLOAD_ON,
        DEFAULT_VALUE_PAYLOAD_OPEN,
        DEFAULT_VALUE_PAYLOAD_OSCILLATION_OFF,
        DEFAULT_VALUE_PAYLOAD_OSCILLATION_ON,
        DEFAULT_VALUE_PAYLOAD_PAUSE,
        DEFAULT_VALUE_PAYLOAD_STOP,
        DEFAULT_VALUE_PAYLOAD_START,
        DEFAULT_VALUE_PAYLOAD_START_PAUSE,
        DEFAULT_VALUE_PAYLOAD_RETURN_TO_BASE,
        DEFAULT_VALUE_PAYLOAD_TURN_OFF,
        DEFAULT_VALUE_PAYLOAD_TURN_ON,
        DEFAULT_VALUE_PAYLOAD_UNLOCK,
        DEFAULT_VALUE_POSITION_CLOSED,
        DEFAULT_VALUE_POSITION_OPEN,
        DEFAULT_VALUE_POWER_COMMAND_TOPIC,
        DEFAULT_VALUE_POWER_STATE_TOPIC,
        DEFAULT_VALUE_POWER_STATE_TEMPLATE,
        DEFAULT_VALUE_RED_TEMPLATE,
        DEFAULT_VALUE_RETAIN,
        DEFAULT_VALUE_RGB_COMMAND_TEMPLATE,
        DEFAULT_VALUE_RGB_COMMAND_TOPIC,
        DEFAULT_VALUE_RGB_STATE_TOPIC,
        DEFAULT_VALUE_RGB_VALUE_TEMPLATE,
        DEFAULT_VALUE_SEND_COMMAND_TOPIC,
        DEFAULT_VALUE_SEND_IF_OFF,
        DEFAULT_VALUE_SET_FAN_SPEED_TOPIC,
        DEFAULT_VALUE_SET_POSITION_TEMPLATE,
        DEFAULT_VALUE_SET_POSITION_TOPIC,
        DEFAULT_VALUE_POSITION_TOPIC,
        DEFAULT_VALUE_SPEED_COMMAND_TOPIC,
        DEFAULT_VALUE_SPEED_STATE_TOPIC,
        DEFAULT_VALUE_SPEED_VALUE_TEMPLATE,
        DEFAULT_VALUE_SPEEDS,
        DEFAULT_VALUE_SOURCE_TYPE,
        DEFAULT_VALUE_STATE_CLOSED,
        DEFAULT_VALUE_STATE_CLOSING,
        DEFAULT_VALUE_STATE_OFF,
        DEFAULT_VALUE_STATE_ON,
        DEFAULT_VALUE_STATE_OPEN,
        DEFAULT_VALUE_STATE_OPENING,
        DEFAULT_VALUE_STATE_LOCKED,
        DEFAULT_VALUE_STATE_UNLOCKED,
        DEFAULT_VALUE_STATE_TOPIC,
        DEFAULT_VALUE_STATE_TEMPLATE,
        DEFAULT_VALUE_STATE_VALUE_TEMPLATE,
        DEFAULT_VALUE_SUBTYPE,
        DEFAULT_VALUE_SUPPORTED_FEATURES,
        DEFAULT_VALUE_SWING_MODE_COMMAND_TOPIC,
        DEFAULT_VALUE_SWING_MODE_STATE_TEMPLATE,
        DEFAULT_VALUE_SWING_MODE_STATE_TOPIC,
        DEFAULT_VALUE_TEMPERATURE_COMMAND_TOPIC,
        DEFAULT_VALUE_TEMPERATURE_HIGH_COMMAND_TOPIC,
        DEFAULT_VALUE_TEMPERATURE_HIGH_STATE_TEMPLATE,
        DEFAULT_VALUE_TEMPERATURE_HIGH_STATE_TOPIC,
        DEFAULT_VALUE_TEMPERATURE_LOW_COMMAND_TOPIC,
        DEFAULT_VALUE_TEMPERATURE_LOW_STATE_TEMPLATE,
        DEFAULT_VALUE_TEMPERATURE_LOW_STATE_TOPIC,
        DEFAULT_VALUE_TEMPERATURE_STATE_TEMPLATE,
        DEFAULT_VALUE_TEMPERATURE_STATE_TOPIC,
        DEFAULT_VALUE_TILT_CLOSED_VALUE,
        DEFAULT_VALUE_TILT_COMMAND_TOPIC,
        DEFAULT_VALUE_TILT_INVERT_STATE,
        DEFAULT_VALUE_TILT_MAX,
        DEFAULT_VALUE_TILT_MIN,
        DEFAULT_VALUE_TILT_OPENED_VALUE,
        DEFAULT_VALUE_TILT_OPTIMISTIC,
        DEFAULT_VALUE_TILT_STATUS_TOPIC,
        DEFAULT_VALUE_TILT_STATUS_TEMPLATE,
        DEFAULT_VALUE_TOPIC_TOPIC,
        DEFAULT_VALUE_UNIQUE_ID,
        DEFAULT_VALUE_UNIT_OF_MEASUREMENT,
        DEFAULT_VALUE_VALUE_TEMPLATE,
        DEFAULT_VALUE_WHITE_VALUE_COMMAND_TOPIC,
        DEFAULT_VALUE_WHITE_VALUE_SCALE,
        DEFAULT_VALUE_WHITE_VALUE_STATE_TOPIC,
        DEFAULT_VALUE_WHITE_VALUE_TEMPLATE,
        DEFAULT_VALUE_XY_COMMAND_TOPIC,
        DEFAULT_VALUE_XY_STATE_TOPIC,
        DEFAULT_VALUE_XY_VALUE_TEMPLATE,
        DEFAULT_VALUE_TYPE,
        DEFAULT_VALUE_STYPE,
        DEFAULT_VALUE_STATE_CLASS};

} // namespace HALIB_NAMESPACE