@startuml
title HommeAssistant Loop

actor HAServer


box "Arduino" #00878F
participant ArduinoCore
participant main
participant WIFI
participant PubSubClient
end box

box "library" #62AEB2
participant HADevice
participant HAAdapter
end box

box "homeassistant" #3eb7ed
participant HANode
participant HAComponent
participant HAComponentDeviceTrigger
end box

ArduinoCore->main : loop
activate main

alt for all adapters
    main->HAAdapter : loop
    activate HAAdapter
    note right : example of implementation
    HAAdapter->ArduinoCore : readDigital
    alt is DI state change
        HAAdapter->HAComponentDeviceTrigger : trigEvent
        activate HAComponentDeviceTrigger
        note right : build message\nfor HA Server
        HAComponentDeviceTrigger->HANode : postMessage
        return
    end
    return
end

ArduinoCore<--main :
deactivate main

ArduinoCore->main : loop
activate main
main->HADevice : loop
activate HADevice

HADevice->WIFI : status
alt WIFI connected
    alt MQTT connected

        HADevice->HANode:pickupOutboxMessage
        activate HANode
        HADevice<--HANode:
        deactivate HANode
        HADevice->PubSubClient:publish
        activate PubSubClient
        HAServer\\--PubSubClient:postMessage
        note left : message will be\nreceived by HA Server
        return

    end
end

return
return


@enduml