@startuml
title HommeAssistant Message management\nFrom HA Server

box "Arduino" #00878F
participant PubSubClient
end box

box "library" #62AEB2
participant HADevice
participant HAAdapter
end box

box "homeassistant" #3eb7ed 
participant HANode
participant HAComponent
end box

PubSubClient -> HADevice : onMQTTMessage
  activate HADevice
  HADevice -> HANode : onMQTTMessage
    activate HANode
    loop "for each components"
    HANode -> HAComponent : onMQTTMessage
    activate HAComponent
      alt message managed
      HANode <-- HAComponent : true
      else message not managed
      HANode <-- HAComponent : false
      deactivate HAComponent
    end
    return
  return
@enduml