@startuml
title Loop

box "Arduino" #00878F
participant ArduinoCore
participant main
participant WIFI
participant PubSubClient
end box

box "library" #62AEB2
participant HADevice
participant HAAdapter
end box

box "homeassistant" #3eb7ed
participant HANode
participant HAComponent
end box

ArduinoCore->main : loop
activate main

main->HADevice : loop
activate HADevice
HADevice->WIFI : status
activate WIFI
return

alt Wifi Connected

  alt MQTT NOT connected

    HADevice->HADevice:prepareMQTTInfo
    HADevice->PubSubClient:connect

    HADevice->HADevice:sendAvailability
    activate HADevice
    HADevice->PubSubClient:publish
    deactivate HADevice

    HADevice->HANode:onHAConnect
    activate HANode
    loop for all component
      HANode->HAComponent:_onHAConnect
      activate HAComponent
      alt is first connection
        HAComponent->HANode:postDiscoveryMessage
        activate HANode
        HANode->HAComponent:buildDiscoveryMessage
        activate HAComponent
        return
        HANode->HANode:patchMessagesWithDeviceInfo
        HANode->HANode:postMessage
        return
      end

      HAComponent->HAComponent:onHAConnect
      activate HAComponent
      
      HAComponent->HAComponent:publishState
      note right : following depends\nof component\nimplementation
      activate HAComponent
        HAComponent->HANode:postMessage
        activate HANode
         return
      deactivate HAComponent
      deactivate HAComponent
      
      HANode<--HAComponent:
      deactivate HAComponent
    end
    HADevice<--HANode:
    deactivate HANode

  else MQTT connected
    
    HADevice->HADevice:treatActions
    activate HADevice
      HADevice->HANode:actionsSize
      activate HANode
      return
      loop actions
        
        HADevice->HANode:pickupAction
        activate HANode
        HADevice<--HANode:
        deactivate HANode
        alt
          HADevice->PubSubClient:subscribe
          activate PubSubClient
          return
        else
          HADevice->PubSubClient:unsubscribe
          activate PubSubClient
          return
        else
          HADevice->PubSubClient:publish
          activate PubSubClient
          return
        end
        alt failed
          HADevice->HANode:retryAction
          activate HANode
          return
        end
      end
    deactivate HADevice
  end
end

main<--HADevice:
deactivate HADevice

alt for all adapters
  main->HAAdapter : loop
  activate HAAdapter
  note right : Do Adapter stuff here
  return
end



ArduinoCore<--main :
deactivate main
@enduml